src/go/k8s/internal/controller/redpanda/redpanda_decommission_controller.go

During decommission nodes Redpanda health response can return nodes that are
starting and they are included to NodesDown part of the response. The logic
should check all NodesIDs in each Redpanda to filter nodes that could start, but
should not be decommissioned.

Do not decommission NodesDown that are starting

---

src/go/k8s/api/vectorized/v1alpha1/console_enterprise_types.go
src/go/k8s/api/vectorized/v1alpha1/zz_generated.deepcopy.go
src/go/k8s/config/crd/bases/redpanda.vectorized.io_consoles.yaml
src/go/k8s/pkg/console/configmap.go
src/go/k8s/pkg/console/console.go

In some cases, we need to tweak the timeout.

operator v1: add console scrape timeout field

---

.buildkite/pipeline.yml
src/go/k8s/api/redpanda/v1alpha1/redpanda_clusterspec_types.go
src/go/k8s/api/redpanda/v1alpha1/zz_generated.deepcopy.go
src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
src/go/k8s/tests/e2e/decommission-on-delete/02-assert.yaml
src/go/k8s/tests/e2e/decommission-on-delete/02-probe.yaml
src/go/k8s/tests/e2e/decommission-on-delete/06-clean.yaml

Fixes https://github.com/redpanda-data/helm-charts/issues/1260

Add Tiered Storage config options for Azure

---

src/go/k8s/api/redpanda/v1alpha1/redpanda_clusterspec_types.go
src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml

Fixes https://github.com/redpanda-data/helm-charts/issues/1240
Should require a release, crds must be updated.

Security context was wrong in json output

---

.github/workflows/comment_added.yml
.github/workflows/jira_issue_manage.yml
.github/workflows/scripts/jira_helper.py
.github/workflows/scripts/requirements.txt

Added workflows to sync GH issues with Jira

gh: Added workflows for Jira issue sync

---

.buildkite/pipeline.yml
src/go/k8s/pkg/resources/statefulset.go
src/go/k8s/tests/e2e/endpoint-template/00-assert.yaml
src/go/k8s/tests/e2e/endpoint-template/01-assert.yaml
taskfiles/k8s.yml

#206 got merged, even with red tests. this should not have happened. this PR fixes the problem.

Fixup for #206

---

src/go/k8s/pkg/console/configmap.go

This is now possible, since we have https://github.com/redpanda-data/redpanda-operator/pull/205 .
instead of "guessing" all pods based on replica count, use ClusterIP service as bootstrap server. this will make use of Kafka API's Service Discovery.
Once we can also use ServiceDiscovery for ADMIN API , scaling will not recreate console CM + pods anymore.

operator v1: use kafka API static ClusterIP svc for console

---

.github/CODEOWNERS

Add Andrew to codeonwers

---

.github/workflows/comment_added.yml
.github/workflows/dispatch-crd-docs.yml
.github/workflows/jira_issue_manage.yml

jira: [PESDLC-1735]
use [oidc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to retrieve secrets
[PESDLC-1735]: https://redpandadata.atlassian.net/browse/PESDLC-1735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

gha: use oidc

---

operator/internal/controller/redpanda/user_controller.go

A previous local build of the operator seemed like it might have occasionally been having terminal errors swallowed (maybe the terminal error checking is too inclusive as it didn't seem like the cluster was dead?) and allowing a user CRD to be deleted without deleting it from the cluster. This adds more logging to make sure we can actually see if this is occurring or if it was just a one-off oddity/now defunct code.

Add extra logging when cleaning up users and potentially swallowing errors for auditability

---

operator/internal/controller/redpanda/redpanda_controller.go
operator/internal/controller/redpanda/redpanda_controller_test.go

This commit implements garbage collection of objects that cease to be rendered by the redpanda helm chart. It does so by listing all objects that match flux's label selector, checking for ownership, and finally against an in memory map of recently created objects.

v2: add object GC'ing in defluxed mode

---

acceptance/features/schema-crds.feature
acceptance/features/topic-crds.feature
acceptance/features/user-crds.feature

JSON type was added here: https://github.com/redpanda-data/redpanda-operator/pull/299

Add new JSON schema type to acceptance test

---

go.work.sum
operator/api/redpanda/v1alpha2/redpanda_types.go
operator/config/crd/bases/cluster.redpanda.com_redpandas.yaml
operator/go.mod
operator/go.sum
operator/internal/controller/redpanda/index.go
operator/internal/controller/redpanda/redpanda_controller.go
operator/internal/controller/redpanda/redpanda_controller_test.go
taskfiles/k8s.yml

Reference:
https://github.com/redpanda-data/helm-charts/pull/1606
https://github.com/redpanda-data/helm-charts/pull/1604
https://github.com/redpanda-data/helm-charts/pull/1607
[K8S-422]
[K8S-422]: https://redpandadata.atlassian.net/browse/K8S-422

Sync helm-chart depedency to include Connectors chart

---

.buildkite/pipeline.yml
ci/scripts/tag-check.sh
taskfiles/ci.yml
taskfiles/k8s.yml

This change is waiting for configurator docker hub container registry repository. 
[K8S-440]
[K8S-440]: https://redpandadata.atlassian.net/browse/K8S-440

Create pipeline for nightly build release

---

operator/cmd/run/run.go

This commit allows the pvcunbinder to be run when the operator is in v2 mode by specifying the `--unbind-pvcs-after` flag to a non-zero value.
This configuration is not formally tested nor supported at this time.

operator: allow the pvcunbinder to run in v2

---

operator/api/redpanda/v1alpha2/redpanda_types.go
operator/config/crd/bases/cluster.redpanda.com_redpandas.yaml

Related to https://github.com/redpanda-data/docs/pull/916

Mark `useFlux` as beta

---

charts/operator/Chart.yaml
charts/operator/README.md
charts/operator/testdata/kustomization.yaml
charts/redpanda/README.md
charts/redpanda/testdata/template-cases.golden.txtar
charts/redpanda/values.yaml

Reference
https://github.com/redpanda-data/helm-charts/pull/1631
[K8S-472]
[K8S-472]: https://redpandadata.atlassian.net/browse/K8S-472

Carry over changes from helm-chart repo

---

Taskfile.yml
flake.nix
licenses/third_party.md
licenses/third_party.md.tpl

And auto generated using the go-licenses tool

licenses: update third party licenses to be correct

---

operator/internal/decommissioning/pvcunbinder.go

Clearing claimRef makes the PV get automatically get re-used by new PVCs, if the hostname matches. This can cause problems, if the same hostname is re-used. It then gets automatically attached to the PVC on that host. In this case, local-path-provisioner's helper pod does not run, and therefore does not mkdir 777. The result is missing permissions, and a crash loop of Redpanda.
This patch removes the clearing of ClaimRef. We want to keep the PV around for possible (but highly unlikely) cases where PVC unbinder made a wrong choice. At this point, a human needs to be involved, so there is no benefit in making the PV auto attach.
Note: We are also exploring using EC2 instance ID as node name, it can also help prevent such edge cases. But ultimately, we believe not setting claimRef …

PVC Unbinder: do not clear claimRef

---

charts/redpanda/go.mod
charts/redpanda/go.sum
pkg/lint/lint_test.go

Create follow up based on TODOs from https://github.com/redpanda-data/redpanda-operator/pull/412

Remove go replace directives

---

operator/internal/controller/redpanda/redpanda_controller.go

Prior to this change, the helper `rateLimitCondition` would return `true` regardless of the readiness of Redpanda. This lead to needless failed connections and a lot of log spam.
This change hoists the check of redpanda's readiness ahead of all other checks to resolve any log spamminess.

operator: hoist dependency on redpanda ready

---

operator/cmd/sidecar/sidecar.go
operator/internal/probes/server.go

[backport] Fix up operator sidecar ports to not conflict by default and opt-out of leader election (#441)

---

.github/CODEOWNERS

@gene-redpanda You will be more happy to receive a order of magnitude more Github notification about every PR in redpanda repository, right?

Add Gene Redpanda to code owners

---

operator/cmd/run/run.go
operator/config/e2e-tests/manager.yaml
operator/internal/controller/vectorized/cluster_controller.go
operator/internal/controller/vectorized/cluster_controller_attached_resources.go
operator/internal/controller/vectorized/cluster_controller_configuration.go
operator/internal/controller/vectorized/cluster_controller_configuration_drift.go
operator/internal/controller/vectorized/test/suite_test.go
operator/internal/decommissioning/statefulset_decomissioner.go
operator/pkg/admin/admin.go
operator/pkg/client/cluster.go
operator/pkg/client/factory.go
operator/pkg/client/factory_test.go
operator/pkg/console/admin.go
operator/pkg/console/sasl.go
operator/pkg/resources/resource_integration_test.go
operator/pkg/resources/statefulset.go
operator/pkg/resources/statefulset_scale.go
operator/pkg/resources/statefulset_test.go
operator/pkg/resources/statefulset_update_test.go
operator/webhooks/redpanda/validate_enterprise_test.go

Reference:
https://github.com/redpanda-data/redpanda-operator/pull/430
https://github.com/redpanda-data/redpanda-operator/pull/431
also backport andrew's PR that adds support for the dialer

[backport] v1 ghost broker decommissioner

---

operator/internal/probes/broker.go

Found an issue when attempting to push out the helm release for the redpanda chart due to our chart-tests utilizing an old version of Redpanda that has this bug in it:
https://github.com/redpanda-data/redpanda/pull/24837
This addition works around the otherwise broken API endpoint.

Add initial cluster health overview check for otherwise broken clusters

---

operator/internal/probes/broker.go

Backport of https://github.com/redpanda-data/redpanda-operator/pull/482

[backport] Add initial cluster health overview check for otherwise broken clusters

---

operator/internal/configwatcher/configwatcher.go

This fixes the way that paths are handled for the configwatcher. Previously it was concatenating the watched directory onto the file that was triggering the notification event. When leveraging absolute paths however, the event Name already includes the parent path in it. This was resulting in errors such as:
open /etc/secrets/users/etc/secrets/users/updated-sasl-users.txt: no such file or directory
This remove the concatenation code to properly handle absolute paths.

sidecar: fix relative paths for the configwatcher

---

operator/internal/configwatcher/configwatcher.go

Backport of https://github.com/redpanda-data/redpanda-operator/pull/484

[backport] sidecar: fix relative paths for the configwatcher

---

pkg/kube/dialer.go
pkg/kube/dialer_test.go

- [pkg/kube: support nested dialers](https://github.com/redpanda-data/redpanda-operator/pull/502)

[release/v2.3.x] pkg/kube: support nested dialers

---

charts/redpanda/Chart.yaml

Changing description to "AI Data platform" from "Real-time engine"

Update Chart.yaml - Update descriptions

---

charts/redpanda/Chart.yaml

Reverts redpanda-data/redpanda-operator#509

Revert "Update Chart.yaml - Update descriptions"

---

.github/workflows/changelog.yml

jira: [DEVPROD-2753]
See https://github.com/tj-actions/changed-files/releases/tag/v46.0.1
[DEVPROD-2753]: https://redpandadata.atlassian.net/browse/DEVPROD-2753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

gha: latest tj-actions/changed-files

---

.github/workflows/changelog.yml

jira: [DEVPROD-2753]
This is a backport of PR #533
See https://github.com/tj-actions/changed-files/releases/tag/v46.0.1
(cherry picked from commit 4cdb6fda0a03537865dd798c64b2d30418c7cebd)
[DEVPROD-2753]: https://redpandadata.atlassian.net/browse/DEVPROD-2753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[release/v2.3.x] gha: latest tj-actions/changed-files

---

charts/console/chart_test.go
charts/console/client_test.go
charts/console/go.mod

https://redpandadata.atlassian.net/browse/CONSOLE-146
This is a basic integration test for Console chart with a good starting point.
It deploys Console and calls the debug HTTP endpoint and verifies an expected string.
I can improve the test to check more of the values and their reconciliation.

console v3 chart integration test

---

operator/internal/controller/redpanda/redpanda_controller.go

- [operator: Return errors with stacktrace](https://github.com/redpanda-data/redpanda-operator/pull/573)

[release/v2.3.x] operator: Return errors with stacktrace

---

.changes/unreleased/operator-Fixed-20250328-112231.yaml
operator/CHANGELOG.md
operator/cmd/run/run.go

We have to kick these off to pick up changes.

Start certificate watchers

---

.changes/unreleased/operator-Removed-20250325-131148.yaml
operator/CHANGELOG.md
operator/api/vectorized/v1alpha1/cluster_webhook.go
operator/internal/controller/vectorized/cluster_controller.go
operator/internal/controller/vectorized/cluster_controller_configuration.go
operator/internal/controller/vectorized/test/cluster_controller_scale_test.go
operator/internal/controller/vectorized/test/cluster_controller_test.go
operator/pkg/resources/configmap.go
operator/pkg/resources/configuration/configuration.go
operator/pkg/resources/configuration/configuration_test.go
operator/pkg/resources/featuregates/featuregates.go
operator/pkg/resources/featuregates/featuregates_test.go
operator/pkg/resources/statefulset.go
operator/pkg/resources/statefulset_scale.go
operator/pkg/resources/statefulset_test.go
operator/pkg/resources/statefulset_update.go

As per the discussion, these gates all encompass "legacy" versions that are no longer supported.
Leave the featuregates package around for the moment should we introduce more.

V1 tidy feature gates

---

.buildkite/pipeline.yml
.golangci.yml
acceptance/go.mod
alias/go.mod
charts/connectors/go.mod
charts/console/go.mod
charts/operator/go.mod
charts/redpanda/go.mod
ci/scripts/run-in-nix-docker.sh
flake.lock
flake.nix
gen/go.mod
gen/partial/partial.go
gotohelm/ast.go
gotohelm/cmd/gotohelm/main.go
gotohelm/go.mod
gotohelm/helmette/sprig.go
gotohelm/testdata/src/example/go.mod
harpoon/go.mod
licenseupdater/config.go
licenseupdater/go.mod
operator/cmd/envsubst/envsubst.go
operator/go.mod
operator/internal/testutils/delete_all_in_namespace.go
operator/pkg/clusterconfiguration/expander.go
pkg/go.mod
pkg/kube/dialer.go
pkg/lint/lint_test.go
pkg/lint/testdata/tool-versions.txtar
taskfiles/ci.yml

Successful run https://buildkite.com/redpanda/redpanda-operator/builds/5336
https://hub.docker.com/layers/redpandadata/redpanda-operator-nightly/v0.0.0-f5dd61d7/images/sha256-9be8c95785e2ab23d1214901e9f3019e1bec890df22e59400ed0d6baae00db8f
https://hub.docker.com/layers/redpandadata/redpanda-operator-nightly/v0.4.39-132-gf5dd61d7-helm-chart/images/sha256-8e4b4d36a54f762709b1e03f0a966a2f1d2f17cd39c9de8739b6f32f43b501f5

ci: Move authentication to container registry inside nix container

---

operator/pkg/console/configmap_test.go
operator/pkg/console/console.go

To prevent the following error. They are now optional

make scopes in console config optional

---

.changie.yaml
go.work.sum
gotohelm/README.md

There's no meaningful change in the commit. It adds a README.md and changie configuration for future changes. Otherwise it's just a marker for tag.

gotohelm: cut release v1.0.0

---

acceptance/features/migration.feature
acceptance/go.mod
acceptance/steps/cluster.go
acceptance/steps/helm.go
acceptance/steps/k8s.go
acceptance/steps/register.go
harpoon/internal/testing/panic.go

[K8S-425]
[K8S-425]: https://redpandadata.atlassian.net/browse/K8S-425

acceptance-test: Add test that show case migration from helm to operator

---

acceptance/features/migration.feature
acceptance/steps/helm.go
acceptance/steps/register.go

Follow-up of https://github.com/redpanda-data/redpanda-operator/pull/578

acceptance-tests: Rewrite feature scenario to match expected english vocabulary

---

charts/connectors/Chart.yaml
charts/console/Chart.yaml
charts/redpanda/Chart.yaml

The error reported by Artifact.io:
```
error getting logo image https://images.ctfassets.net/paqvtpyf8rwu/3cYHw5UzhXCbKuR24GDFGO/73fb682e6157d11c10d5b2b5da1d5af0/skate-stand-panda.svg: unexpected status code received: 404 (package: redpanda version: 5.10.2)
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid annotation: 1 error occurred:
* invalid image reference: could not parse reference:
(package: operator version: 0.3.2)
```

Change icon URI to new place

---

charts/connectors/Chart.yaml
charts/console/Chart.yaml
charts/redpanda/Chart.yaml

The error reported by Artifact.io:
```
error getting logo image https://images.ctfassets.net/paqvtpyf8rwu/3cYHw5UzhXCbKuR24GDFGO/73fb682e6157d11c10d5b2b5da1d5af0/skate-stand-panda.svg: unexpected status code received: 404 (package: redpanda version: 5.10.2)
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid annotation: 1 error occurred:
* invalid image reference: could not parse reference:
(package: operator version: 0.3.2)
```

[release/v2.3.x] Change icon URI to new place

---

charts/connectors/Chart.yaml
charts/console/Chart.yaml
charts/redpanda/Chart.yaml

The error reported by Artifact.io:
```
error getting logo image https://images.ctfassets.net/paqvtpyf8rwu/3cYHw5UzhXCbKuR24GDFGO/73fb682e6157d11c10d5b2b5da1d5af0/skate-stand-panda.svg: unexpected status code received: 404 (package: redpanda version: 5.10.2)
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid annotation: 1 error occurred:
* invalid image reference: could not parse reference:
(package: operator version: 0.3.2)
```

[release/v2.4.x] Change icon URI to new place

---

operator/pkg/resources/statefulset.go

Replacing #806 which failed to trigger CI for some reason.

v1: fix typo in getConfiguratorArgs

---

charts/redpanda/client/client.go

This adds a panic handler for the call to `authFromDot` it won't stop test flakiness (think that will probably be handled in Jan's PR: #821 due to how he bumped the vcluster installation timeout), but this will make it so we don't get random panics instead of assertion failures in our tests (and proper errors rather than a recovered panic by the runtime if it happens in our controller).

Wrap authFromDot in a panic handler

---

pkg/helm/helm.go
pkg/helm/helm_test.go

Prior to this commit context timeouts resulted in `helm` being SIGKILL'd and the resultant error did not indicate what happened nor why.
This commit updates the helm runner to first SIGINT `helm` and to SIGKILL it after 5s. Additionally the context error is now included in the error chain to further clarify what happened.

pkg/helm: gracefully shutdown on timeout

---

operator/internal/controller/redpanda/redpanda_controller_test.go

This wraps the initial version fetching code for our cluster settings tests in a retry block. What I've noticed is that due to the asynchronous nature of reconciliation there are some times where our status conditions show pods as stable right before they restart. When this happens we wind up with a test failure due to an EOF error (because of a restarting broker) in the `ClusterConfigStatus` request, and then, due to `st` being empty in the case of an error, a panic.
This fixes it by just retrying in the case of an error.

Test fix: wrap initial version fetching in retry block
